# Configuration script for Travis CI.
# Instructions to install the MPI implementation
# were taken from https://github.com/bsamseth/mpi4py-travis/

language: python
python:
  - "3.7"

dist: xenial

cache:
  directories:
    - $TRAVIS_BUILD_DIR/openmpi-build
    - $TRAVIS_BUILD_DIR/openmpi-3.1.3

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gfortran-9
      env:
        - C_COMPILER="gcc-9", CXX_COMPILER="g++-9", FORTRAN_COMPILER="gfortran-9"

before_install:
  - python -m pip --version
  - python -m pip install --upgrade pip
  - python -m pip --version
  - python -m pip install build
  - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/openmpi-build
  - export MPI_VERSION="4.0"
  - export MPI_FULL_VERSION="4.0.5"
install:
  - python -m pip install obspy
  - source ci/install-openmpi.sh
  - echo $MPI_FC
  - echo $MPI_EXEC
  - env MPICC=$MPI_CC MPIFORT=$MPI_FC python -m pip install mpi4py
  - env MPICC=$MPI_CC MPIFORT=$MPI_FC python -m pip install .

script:
  - pytest
