language: python
python:
  - "3.7"
dist: xenial
notifications:
  email: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/openmpi-build
    - $TRAVIS_BUILD_DIR/openmpi-3.1.3

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.7-dev
            - g++-7
      env:
        - C_COMPILER="gcc-7", CXX_COMPILER="g++-7"

before_install:
  - pyenv global $(pyenv whence 2to3)
  - pip install pipenv
  - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/openmpi-build
  - export MPI_VERSION="3.1"
  - export MPI_FULL_VERSION="3.1.3"

install:
  # Non-cached builds can take some time. Tell Travis not to time out (30 min should be plenty).
  - source ci/install-openmpi_test.sh
  - echo $MPI_CC
  - echo $MPI_CXX
  - echo $MPI_EXEC
  - env PIPENV_IGNORE_VIRTUALENVS=1 MPICC=$MPI_CC pipenv install --skip-lock
