# Configuration script for Travis CI.
# Instructions to install the MPI implementation
# were taken from https://github.com/bsamseth/mpi4py-travis/

language: python
python:
  - "3.7"

dist: xenial

cache:
  directories:
    - $TRAVIS_BUILD_DIR/openmpi-build
    - $TRAVIS_BUILD_DIR/openmpi-3.1.3

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER="gcc", CXX_COMPILER="g++", FORTRAN_COMPILER="gfortran"

before_install:
  - python -m pip install build
  - python -m pip --version
  - python -m pip install --upgrade pip
  - python -m pip --version
  - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/openmpi-build
  - export MPI_VERSION="3.1"
  - export MPI_FULL_VERSION="3.1.3"
install:
  - source ci/install-openmpi.sh
  - echo $MPI_FORTRAN
  - echo $MPI_EXEC
  - env MPICC=$MPI_CC MPIFORT=$MPI_FORTRAN python -m pip install .

script:
  - pytest
